services:
  db:
    image: postgres:16
    container_name: kbqa_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./sql.init:/docker-entrypoint-initdb.d:ro   # <â€” changed

  pgadmin:
    image: dpage/pgadmin4
    container_name: kbqa_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"   # if 5050 is busy on your PC, change to "5051:80"
volumes:
  dbdata:
